"""Component property atlas: attach each component class to a throw-away entity and record
its editable properties (name, type, default value, read-only) and any components that came along.

Results are cached incrementally in a JSON file so a crash in the editor loses nothing.
"""
import json
import os
import time

from . import api

ENTITY = {"refPath": "/EntityFramework/_Verse/VNI/Entity.entity"}
SKIP = ("ItemizationTests_", "itemization_debug", "NexusFramework", "screenshot_test", "Simulation_", "level_subsim",
        "PlayspaceInternal")


# AddComponent on a fresh entity crashed UEFN 42.30 for these (never probe them blindly again)
CRASHES = {"UI_grid_container_component"}


def _xf(x=0, y=0, z=-20000):
    return {"location": {"x": x, "y": y, "z": z}, "rotation": {"pitch": 0, "yaw": 0, "roll": 0},
            "scale": {"x": 1, "y": 1, "z": 1}}


def probe(cls_path, name="__atlas_probe"):
    ent = api.tool("entity", "CreateEntity", {"entityClass": ENTITY, "name": name, "transform": _xf()})["entity"]
    try:
        before = {c["componentClass"]["refPath"] for c in api.tool("entity", "GetComponents", {"entity": ent})}
        added = api.tool("entity", "AddComponent", {"entity": ent, "componentClass": {"refPath": cls_path}})
        comps = api.tool("entity", "GetComponents", {"entity": ent})
        extra = [c["componentName"] for c in comps
                 if c["componentClass"]["refPath"] not in before and c["componentClass"]["refPath"] != cls_path]
        props = api.tool("entity", "ListComponentProperties", {"component": added["component"]})
        return {"props": props, "auto_added": extra}
    finally:
        api.tool("entity", "DeleteEntity", {"entity": ent})


def build(out_json, filt=""):
    data = {}
    if os.path.exists(out_json):
        with open(out_json, encoding="utf-8") as f:
            data = json.load(f)
    classes = api.tool("entity", "ListComponentClasses", {"nameFilter": filt})
    for c in sorted(classes, key=lambda c: c["classPath"]["refPath"]):
        path, name = c["classPath"]["refPath"], c["className"]
        if path in data or any(s in name for s in SKIP):
            continue
        if name in CRASHES:
            print(f"{name:55s} SKIP (crashed the editor before)")
            continue
        t = time.time()
        try:
            r = probe(path)
        except Exception as e:
            r = {"error": str(e)[:600]}
        r["name"] = name
        r["secs"] = round(time.time() - t, 2)
        data[path] = r
        print(f"{name:55s} {('ERR ' + r['error'][:80]) if 'error' in r else str(len(r['props'])) + ' props'}", flush=True)
        with open(out_json, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=1)
    return data


def verse_visible(names):
    """Which component class names appear as classes in the Verse digests (i.e. usable from Verse code)."""
    import re as _re
    from . import digest
    txt = chr(10).join(open(f, encoding="utf-8").read() for f in digest.digest_files())
    vis = set()
    for n in names:
        base = n.split("-")[-1]
        cands = {base}
        m = _re.match(r"^[A-Z][A-Za-z]+_(.+)$", base)
        if m:
            cands.add(m.group(1))
        if any(_re.search(_re.escape(c) + r"<[^\n]*:= class", txt) for c in cands):
            vis.add(n)
    return vis


def to_markdown(data):
    groups = {}
    for path, r in data.items():
        plugin = path.split("/")[1]
        groups.setdefault(plugin, []).append((r.get("name", path), path, r))
    vis = verse_visible([r.get("name", "") for r in data.values()])
    out = ["# Scene Graph component atlas (UEFN 42.30)", "",
           "Generated by `uefn sg atlas`: every attachable component class was added to a fresh entity and its",
           "editable properties were read back with `ListComponentProperties`. Values are the editor defaults",
           "(JSON as accepted by `SetComponentProperty`). `auto` = components that were added along with it.",
           "**Verse ✅** = the class exists in the Verse digests, so Verse code can construct/find it; *editor-only* classes",
           "can be placed with the EntityToolset but not referenced from Verse.", ""]
    for plugin in sorted(groups):
        out += [f"## {plugin}", ""]
        for name, path, r in sorted(groups[plugin]):
            tag = "Verse ✅" if name in vis else "editor-only (not in Verse digests)"
            out.append(f"### `{name}`")
            out.append(f"`{path}` — {tag}")
            out.append("")
            if "error" in r:
                out += ["Add failed: `" + r["error"].replace("\n", " ")[:300] + "`", ""]
                continue
            if r.get("auto_added"):
                out += ["auto: " + ", ".join(f"`{a}`" for a in r["auto_added"]), ""]
            if not r["props"]:
                out += ["_no editable properties_", ""]
                continue
            out += ["| property | type | default | ro |", "|---|---|---|---|"]
            for p in r["props"]:
                v = str(p.get("value", "")).replace("|", "\\|").replace("\n", " ")
                if len(v) > 120:
                    v = v[:117] + "..."
                t = str(p.get("type", "")).replace("|", "\\|")
                out.append(f"| `{p['name']}` | `{t}` | `{v}` | {'ro' if p.get('bReadOnly') else ''} |")
            out.append("")
    return "\n".join(out) + "\n"
