"""Dump every toolset's tools + schemas into readable Markdown (and raw JSON) in the repo."""
import json
import os

from . import api


def _type(s):
    if not isinstance(s, dict):
        return "?"
    if "title" in s and s.get("type") == "object" and "refPath" in s.get("properties", {}):
        return f"ref<{s['title']}>"
    t = s.get("type")
    if t == "array":
        return f"[{_type(s.get('items', {}))}]"
    if t == "object":
        props = s.get("properties", {})
        if s.get("title") and len(props) > 4:
            return s["title"]
        inner = ", ".join(f"{k}:{_type(v)}" for k, v in props.items())
        return (s.get("title", "") + "{" + inner + "}") if props else (s.get("title") or "object")
    if "enum" in s:
        return "|".join(map(str, s["enum"]))
    if "anyOf" in s:
        return " or ".join(_type(x) for x in s["anyOf"])
    return t or s.get("title", "?")


def tool_md(t):
    short = t["name"].split(".")[-1]
    schema = t.get("inputSchema", {})
    req = set(schema.get("required", []))
    lines = [f"### `{short}`", "", t.get("description", "").strip(), ""]
    props = schema.get("properties", {})
    if props:
        lines.append("| arg | type | req | description |")
        lines.append("|---|---|---|---|")
        for k, v in props.items():
            d = (v.get("description", "") or "").replace("\n", " ").replace("|", "\\|")
            if "default" in v:
                d += f" (default `{json.dumps(v['default'])}`)"
            lines.append(f"| `{k}` | `{_type(v).replace('|', ' or ')}` | {'yes' if k in req else ''} | {d} |")
        lines.append("")
    out = t.get("outputSchema", {}).get("properties", {}).get("returnValue")
    if out:
        lines.append(f"Returns: `{_type(out).replace('|', ' or ')}`")
        lines.append("")
    return "\n".join(lines)


def dump(outdir, names=None):
    os.makedirs(os.path.join(outdir, "json"), exist_ok=True)
    names = names or api.toolset_names(refresh=True)
    index = ["# Toolset catalog", "", "Generated by `uefn catalog` from the live editor. One file per toolset.", "",
             "| Toolset | Tools |", "|---|---|"]
    for n in names:
        try:
            d = api.describe(n)
        except Exception as e:  # hidden / failing toolsets are recorded, not fatal
            index.append(f"| {n} | ERROR {str(e)[:80]} |")
            continue
        with open(os.path.join(outdir, "json", n + ".json"), "w", encoding="utf-8") as f:
            json.dump(d, f, indent=1)
        tools = sorted(d.get("tools", []), key=lambda t: t["name"])
        md = [f"# {n}", "", d.get("description", "").strip(), "", f"{len(tools)} tools.", ""]
        md += [tool_md(t) for t in tools]
        with open(os.path.join(outdir, n + ".md"), "w", encoding="utf-8") as f:
            f.write("\n".join(md))
        shorts = ", ".join(t["name"].split(".")[-1] for t in tools)
        index.append(f"| [{n}]({n}.md) | {shorts} |")
    with open(os.path.join(outdir, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(index) + "\n")
    return names
